import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ChakraThemeProviders } from "@/provider/chakra-provider";
import ChatProvider from "@/provider/chat-peovider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChakraThemeProviders>
          <ChatProvider>{children}</ChatProvider>
        </ChakraThemeProviders>
      </body>
    </html>
  );
}
